### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/fancy-hover-boxes#1]
@hellachella
@HannahDelaney
@mackenzierose
I've followed the steps exactly, but for some reason the images seem to be larger than their supposed to be. Were they supposed to be compress to a smaller size or is their something else that I have to do.

**Comment by HannahDelaney** [comment]
So sorry to have missed this one this morning!

You haven't given your images a width or display type, and so they are not showing the full image but are cutting off where the column definition ends.

Add this to your css:

```
img {
  width: 100%;
  display: block;
}
```

**Comment by AlexanderTahtadjian** [comment]
Thanks it works now
